import type { Metadata } from 'next'
import './globals.css'
import LayoutWrapper from '@/components/LayoutWrapper'
import QueryProviders from '@/components/QueryProviders'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body
        className={`antialiased bg-[url(/images/bg.png)] bg-contain bg-repeat `}
      >
        <QueryProviders>
          <LayoutWrapper>{children}</LayoutWrapper>
        </QueryProviders>
      </body>
    </html>
  )
}
